# Generated by Django 3.2.4 on 2021-08-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_song',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
